services:
  backend:
    image: ghcr.io/${GHCR_USERNAME:-abhinav162}/resumate-backend:latest
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "4300:4300"
    environment:
      - NODE_ENV=production
      - PORT=4300
    env_file:
      - apps/backend/.env
    volumes:
      - ./data:/app/data
    restart: always

  frontend:
    image: ghcr.io/${GHCR_USERNAME:-abhinav162}/resumate-frontend:latest
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3160:80"
    env_file:
      - apps/frontend/.env
    restart: always
    depends_on:
      - backend
